### ISSUE TITLE
Make the stories listing page responsive

### ISSUE THREAD

**Issue by richdouglasevans** [BrookesUniversityLearningResources/vsat#97]
'cos currently it isn't.

## Where?

* [Here](https://github.com/BrookesUniversityLearningResources/vsat/blob/main/src/pages/story/index.astro#L21)

## When Is This Done?

When the stories listing page displays stories:

* in a 3-column layout on larger screens
* in a single-column on smaller (mobile) screens

## How?

Using [media queries](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design#media_queries).

Currently the page is hardcoded to render in a 3-column [grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout):

```css
    display: grid;
    grid-template-columns: 25rem 25rem 25rem;
```

> If you're new to grid layout then working your way through the (short) tutorial at [Grid Garden](https://cssgridgarden.com/) is worth it. I've done it a few times.

What we want is to have 1-, 2-, or 3-columns depending on the width of the (browser) window.

* when the window is small, use 1 column.
* when the window is medium-width, use 2 columns.
* when the window is bigger than medium-width, use 3 columns.

If we start out with a 1-column grid -- for small windows -- then we can have media query breakpoints that change the number of columns as the width increases.

> * [Mobile first design](https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design)

Find below the start to a possible implementation.

<details>
  <summary>Spoiler</summary>
  
```css
  .stories {
    margin: 1rem;

    display: grid;
    gap: 2rem;
    justify-content: center;
  }
```

We can then be explicit about the number of columns as the width increases.

```css
  @media screen and (min-width: 850px) {
    .stories {
      grid-template-columns: 25rem 25rem; /* 2-column */
    }
  }

  @media screen and (min-width: 1250px) {
    .stories {
      /* add code for 3-columns */
    }
  }
```
</details>
